# Generated by Django 3.0.6 on 2020-05-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
